"""
Binding de Learntorch C++
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Adam', 'BackendType', 'Block', 'CONCAT', 'CPU', 'CPU_OPTIMIZED', 'Conv2D', 'CrossEntropy', 'Embedding', 'Flatten', 'GEMM_OPTIMIZED', 'Identity', 'Join', 'JoinMode', 'LayerNorm', 'Linear', 'Loss', 'MSELoss', 'Optimizer', 'Parallel', 'ReLU', 'SGD', 'SUM', 'SelfAttention', 'Serial', 'Sigmoid', 'Softmax', 'Tanh', 'Tensor', 'Trainer', 'argmax', 'exp', 'log', 'matmul', 'max', 'relu', 'set_backend', 'sigmoid', 'sqrt', 'sum', 'tanh', 'transpose']
class Adam(Optimizer):
    def __init__(self, params: collections.abc.Sequence[Tensor], lr: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513, beta1: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421, beta2: typing.SupportsFloat | typing.SupportsIndex = 0.9990000128746033, epsilon: typing.SupportsFloat | typing.SupportsIndex = 9.99999993922529e-09) -> None:
        ...
class BackendType:
    """
    Members:

      CPU

      CPU_OPTIMIZED

      GEMM_OPTIMIZED
    """
    CPU: typing.ClassVar[BackendType]  # value = <BackendType.CPU: 0>
    CPU_OPTIMIZED: typing.ClassVar[BackendType]  # value = <BackendType.CPU_OPTIMIZED: 1>
    GEMM_OPTIMIZED: typing.ClassVar[BackendType]  # value = <BackendType.GEMM_OPTIMIZED: 2>
    __members__: typing.ClassVar[dict[str, BackendType]]  # value = {'CPU': <BackendType.CPU: 0>, 'CPU_OPTIMIZED': <BackendType.CPU_OPTIMIZED: 1>, 'GEMM_OPTIMIZED': <BackendType.GEMM_OPTIMIZED: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
class Block:
    def forward(self, arg0: collections.abc.Sequence[Tensor]) -> list[Tensor]: ...
    def load_weights(self, arg0: str) -> None: ...
    def parameters(self) -> list[Tensor]: ...
    def save_weights(self, arg0: str) -> None: ...
class Conv2D(Block):
    B: Tensor
    W: Tensor
    def __init__(self, in_channels: typing.SupportsInt | typing.SupportsIndex, out_channels: typing.SupportsInt | typing.SupportsIndex, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex, padding: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def padding(self) -> int: ...
    @padding.setter
    def padding(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def stride(self) -> int: ...
    @stride.setter
    def stride(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
class CrossEntropy(Loss):
    def __init__(self) -> None: ...
class Embedding(Block):
    def __init__(self, vocab_size: typing.SupportsInt | typing.SupportsIndex, vector_size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
class Flatten(Block):
    def __init__(self) -> None: ...
class Identity(Block):
    def __init__(self) -> None: ...
class Join(Block):
    def __init__(self, mode: JoinMode = JoinMode.SUM) -> None: ...
class JoinMode:
    """
    Members:

      SUM

      CONCAT
    """
    CONCAT: typing.ClassVar[JoinMode]  # value = <JoinMode.CONCAT: 1>
    SUM: typing.ClassVar[JoinMode]  # value = <JoinMode.SUM: 0>
    __members__: typing.ClassVar[dict[str, JoinMode]]  # value = {'SUM': <JoinMode.SUM: 0>, 'CONCAT': <JoinMode.CONCAT: 1>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
class LayerNorm(Block):
    def __init__(self, embed_dim: typing.SupportsInt | typing.SupportsIndex, epsilon: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-06) -> None: ...
class Linear(Block):
    B: Tensor
    W: Tensor
    def __init__(self, in_features: typing.SupportsInt | typing.SupportsIndex, out_features: typing.SupportsInt | typing.SupportsIndex) -> None: ...
class Loss:
    def forward(self, arg0: Tensor, arg1: Tensor) -> Tensor: ...
class MSELoss(Loss):
    def __init__(self) -> None: ...
class Optimizer:
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
class Parallel(Block):
    def __init__(self, arg0: collections.abc.Sequence[Block]) -> None: ...
class ReLU(Block):
    def __init__(self) -> None: ...
class SGD(Optimizer):
    def __init__(self, params: collections.abc.Sequence[Tensor], lr: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
class SelfAttention(Block):
    k_proj: Linear
    out_proj: Linear
    q_proj: Linear
    v_proj: Linear
    def __init__(self, dim: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def embed_dim(self) -> int: ...
    @embed_dim.setter
    def embed_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
class Serial(Block):
    def __init__(self, arg0: collections.abc.Sequence[Block]) -> None: ...
class Sigmoid(Block):
    def __init__(self) -> None: ...
class Softmax(Block):
    def __init__(self) -> None: ...
class Tanh(Block):
    def __init__(self) -> None: ...
class Tensor:
    @staticmethod
    def ones(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor: ...
    @staticmethod
    def random(shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], min_val: typing.SupportsFloat | typing.SupportsIndex = -1.0, max_val: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> Tensor: ...
    @staticmethod
    def zeros(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor: ...
    @typing.overload
    def __add__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __init__(self, shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] = []) -> None: ...
    def __matmul__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __mul__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __repr__(self) -> str: ...
    def __sub__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __truediv__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def backward(self) -> None: ...
    def data(self) -> list[float]: ...
    def item(self) -> float: ...
    @property
    def grad(self) -> Tensor: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
class Trainer:
    def __init__(self, arg0: Block, arg1: Optimizer, arg2: Loss) -> None: ...
    def fit(self, x_train: Tensor, y_train: Tensor, epochs: typing.SupportsInt | typing.SupportsIndex, batch_size: typing.SupportsInt | typing.SupportsIndex, print_every: typing.SupportsInt | typing.SupportsIndex = 1) -> None: ...
def argmax(tensor: Tensor, dim: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor: ...
def exp(arg0: Tensor) -> Tensor: ...
def log(arg0: Tensor) -> Tensor: ...
def matmul(arg0: Tensor, arg1: Tensor, arg2: bool) -> Tensor: ...
def max(tensor: Tensor, dim: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor: ...
def relu(arg0: Tensor) -> Tensor: ...
def set_backend(arg0: BackendType) -> None: ...
def sigmoid(arg0: Tensor) -> Tensor: ...
def sqrt(arg0: Tensor) -> Tensor: ...
def sum(tensor: Tensor, dim: typing.SupportsInt | typing.SupportsIndex = 0) -> Tensor: ...
def tanh(arg0: Tensor) -> Tensor: ...
def transpose(arg0: Tensor) -> Tensor: ...
CONCAT: JoinMode  # value = <JoinMode.CONCAT: 1>
CPU: BackendType  # value = <BackendType.CPU: 0>
CPU_OPTIMIZED: BackendType  # value = <BackendType.CPU_OPTIMIZED: 1>
GEMM_OPTIMIZED: BackendType  # value = <BackendType.GEMM_OPTIMIZED: 2>
SUM: JoinMode  # value = <JoinMode.SUM: 0>
